/**
 * Engine — reads CONFIG, loads components, renders & animates.
 * DO NOT edit this file for customization. Edit config.js only.
 */

// ── Theme ────────────────────────────────────────────────────────
let currentMode = (CONFIG.defaultMode || "dark");

function applyTheme(mode) {
  currentMode = mode;
  const root = document.documentElement;
  const c = CONFIG.colors;

  root.style.setProperty("--primary", c.primary || "#ff69b4");
  root.style.setProperty("--accent", c.accent || "#15a1ed");

  const theme = c[mode] || c.dark || {};
  root.style.setProperty("--bg", theme.background || "#1a1a2e");
  root.style.setProperty("--text", theme.text || "#ffffff");

  // Update toggle icon
  const btn = document.getElementById("theme-toggle");
  if (btn) btn.textContent = mode === "dark" ? "☀️" : "🌙";
}

function createThemeToggle() {
  const btn = document.createElement("button");
  btn.id = "theme-toggle";
  btn.title = "Toggle dark/light mode";
  btn.textContent = currentMode === "dark" ? "☀️" : "🌙";
  btn.addEventListener("click", () => {
    applyTheme(currentMode === "dark" ? "light" : "dark");
  });
  document.body.appendChild(btn);
}

// ── Script Loader ────────────────────────────────────────────────
function loadScript(src) {
  return new Promise((resolve, reject) => {
    const s = document.createElement("script");
    s.src = src;
    s.onload = resolve;
    s.onerror = () => reject(new Error("Component not found: " + src));
    document.head.appendChild(s);
  });
}

// ── Main ─────────────────────────────────────────────────────────
document.addEventListener("DOMContentLoaded", async () => {
  applyTheme(currentMode);
  createThemeToggle();

  // Set music source
  const audio = document.querySelector(".song");
  if (audio && CONFIG.music) {
    audio.querySelector("source").src = CONFIG.music;
    audio.load();
  }

  // Determine unique component types
  const types = [...new Set(CONFIG.sections.map((s) => s.type))];

  // Dynamically load component scripts
  for (const type of types) {
    try {
      await loadScript(`./script/components/${type}.js`);
    } catch (e) {
      console.warn(e.message);
    }
  }

  // Render all sections
  const container = document.querySelector(".container");
  const rendered = [];

  CONFIG.sections.forEach((section) => {
    const comp = window.Components && window.Components[section.type];
    if (!comp) {
      console.warn(`Component "${section.type}" not found, skipping.`);
      return;
    }
    const el = comp.render(container, section, CONFIG);
    rendered.push({ el, comp, section });
  });

   // SweetAlert music prompt (with mobile rotate handling)
   const isDark = currentMode === "dark";

   function showMusicPrompt() {
     Swal.fire({
       title: "Play music in the background?",
       icon: "question",
       showCancelButton: true,
       confirmButtonColor: CONFIG.colors.accent || "#3085d6",
       cancelButtonColor: "#888",
       confirmButtonText: "Yes!",
       cancelButtonText: "No",
       background: isDark ? "#1e293b" : "#ffffff",
       color: isDark ? "#f1f5f9" : "#1e293b",
     }).then((result) => {
       if (result.isConfirmed && audio) {
         audio.play().catch(() => {});
       }
      // Start the main timeline after the prompt regardless of choice
      try {
        buildTimeline(rendered);
      } catch (e) {
        console.error('Failed to start timeline', e);
      }
     });
   }

   function createRotateOverlay() {
     const overlay = document.createElement('div');
     overlay.id = 'rotate-overlay';
     overlay.style.position = 'fixed';
     overlay.style.inset = '0';
     overlay.style.display = 'flex';
     overlay.style.alignItems = 'center';
     overlay.style.justifyContent = 'center';
     overlay.style.background = 'rgba(0,0,0,0.85)';
     overlay.style.color = '#fff';
     overlay.style.zIndex = '9999';
     overlay.style.textAlign = 'center';
     overlay.style.padding = '1rem';
     overlay.style.fontFamily = 'Poppins, sans-serif';
     overlay.innerHTML = '<div><div style="font-size:1.6rem;margin-bottom:0.5rem">Please rotate your phone</div><div style="opacity:0.95">For the best experience, rotate to landscape and then tap continue.</div></div>';
     document.body.appendChild(overlay);
     return overlay;
   }

   function removeRotateOverlay() {
     const el = document.getElementById('rotate-overlay');
     if (el) el.parentNode.removeChild(el);
   }

   const isMobile = /Mobi|Android|iPhone|iPad|iPod/.test(navigator.userAgent || '');
   const prefersLandscape = window.matchMedia && window.matchMedia('(orientation: landscape)').matches;

   if (isMobile && !prefersLandscape) {
     createRotateOverlay();
     const onOrientation = () => {
       const nowLandscape = window.matchMedia && window.matchMedia('(orientation: landscape)').matches;
       if (nowLandscape) {
         removeRotateOverlay();
         setTimeout(() => {
           showMusicPrompt();
         }, 300);
         window.removeEventListener('orientationchange', onOrientation);
         window.removeEventListener('resize', onOrientation);
       }
     };
     window.addEventListener('orientationchange', onOrientation);
     window.addEventListener('resize', onOrientation);
   } else {
     showMusicPrompt();
   }
});

// ── Timeline Builder ─────────────────────────────────────────────
function buildTimeline(rendered) {
  const tl = gsap.timeline();

  tl.to(".container", { duration: 0.6, visibility: "visible" });

  // Track deferred exits for overlay components
  let deferredExits = [];

  rendered.forEach(({ el, comp, section }, i) => {
    const isOverlay = comp.overlay === true;

    // Flush deferred exits before non-overlay sections
    if (!isOverlay && deferredExits.length > 0) {
      deferredExits.forEach((fn) => fn());
      deferredExits = [];
    }

    // Animate
    comp.animate(tl, el, CONFIG);

    // Handle exit lifecycle
    if (comp.exit) {
      const next = rendered[i + 1];
      const nextIsOverlay = next && next.comp.overlay === true;

      if (nextIsOverlay) {
        deferredExits.push(() => comp.exit(tl, el));
      } else if (!isOverlay) {
        comp.exit(tl, el);
      }
    }
  });

  // Flush remaining
  deferredExits.forEach((fn) => fn());

  // Setup replay
  const replayBtn = document.getElementById("replay");
  if (replayBtn) {
    replayBtn.addEventListener("click", () => tl.restart());
  }
}
